# Generated by Django 5.1.6 on 2025-02-24 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('subject', models.CharField(max_length=50)),
                ('total_questions', models.IntegerField()),
                ('correct_answers', models.IntegerField()),
                ('wrong_answers', models.IntegerField()),
                ('blank_answers', models.IntegerField()),
                ('study_hours', models.FloatField()),
                ('practice_questions', models.IntegerField()),
                ('percentage', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'date', 'subject')},
            },
        ),
    ]
